---
title: erikonijn
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: pages
    type: pages
  values:
    layout: default
    permalink: "/:basename:output_ext"
email: e@ma.il
description: 'erikonijn.

'
baseurl: ''
url: ''
permalink: pretty
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
